export const UsersEndpoints = (uuid?: string) => ({
  TABLE: '/user',
  SELECT: '/user/selectlist',
  USER_INFO: '/user/user-info',
  EXPORT: '/user/export',
  EDIT_PASSWORD: '/user/edit-password',
  DETAIL: `/user/${uuid}`,
  ASSIGN_JOB_POSITIONS: `/user/${uuid}/jobposition`,
  HISTORY: `/user/${uuid}/history`,
  HISTORY_EXPORT: `/user/${uuid}/history/export`,
  AVATAR: `/user/${uuid}/avatar`,
  AVATAR_DOWNLOAD: (fileUuid: string) => `/user/${uuid}/file-avatar-download/${fileUuid}`,
  BACKGROUND: `/user/${uuid}/background`,
  BACKGROUND_DOWNLOAD: (fileUuid: string) => `/user/${uuid}/file-background-download/${fileUuid}`,
  FILE_UPLOAD: `/user/${uuid}/file`,
  FILE_DETAIL: (fileUuid: string) => `/user/${uuid}/file/${fileUuid}`,
  FILE_DOWNLOAD: (fileUuid: string) => `/user/${uuid}/file-download/${fileUuid}`,
  FILE_NEW_VERSION: (fileUuid: string) => `/user/${uuid}/file-new-version/${fileUuid}`,
})
